### ISSUE TITLE
code improvement

### ISSUE THREAD

**Issue by umtkas** [suhabaobaid/Item-Catalog-App#1]
no need to pass dictionary in **jsonify** function
`  return jsonify({"Category": [category.serializeWithoutItems for category in categories]})`

can be written as
`  return jsonify(Category=[category.serializeWithoutItems for category in categories])`

**Comment by suhabaobaid** [comment]
@umtkas cool thanks! This will be a small tutorial article when done. Want to help reviewing when I am done?

**Comment by umtkas** [comment]
sure, why not :)
